apiVersion: v1
kind: Service
metadata:
  name: ft-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: ft-backend
spec:
  selector:
    app: ft-backend
  ports:
    - name: http-django
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: http-istio
      protocol: TCP
      port: 15020
      targetPort: 15020
