apiVersion: apps/v1
kind: Deployment
metadata:
  name: ft-backend
  namespace: "{{ .Values.namespace }}"
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  replicas: {{ .Values.web.replicas | int }}
  selector:
    matchLabels:
      app: ft-backend
      version: v1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: ft-backend
        version: v1
        sidecar.istio.io/inject: "true"
      annotations:
        proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true}'
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: ft-service-account
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - ft-backend
              topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
        - name: ghcr-secret
      securityContext:
        fsGroup: 1000
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
            - |
              python manage.py collectstatic --noinput
              gunicorn ft.wsgi:application --bind 0.0.0.0:8000 --timeout 60
          envFrom:
            - configMapRef:
                name: ft-config
            - secretRef:
                name: ft-secrets
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /api/health_check
              port: 8000
            initialDelaySeconds: 0
            periodSeconds: 1
            timeoutSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /api/health_check
              port: 8000
            initialDelaySeconds: 0
            periodSeconds: 60
            timeoutSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
