apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpt-frontend
  namespace: {{ .Release.Namespace }}
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  replicas: {{ .Values.frontend.replicas | int }}
  selector:
    matchLabels:
      app: tpt-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: tpt-frontend
        version: v1
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      serviceAccountName: tpt-service-account
      securityContext:
        runAsNonRoot: true
        runAsUser: 101  # nginx user
        fsGroup: 101    # nginx group
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: nginx-run
              mountPath: /run/nginx
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu | default "50m" }}
              memory: {{ .Values.frontend.resources.requests.memory | default "64Mi" }}
            limits:
              cpu: {{ .Values.frontend.resources.limits.cpu | default "100m" }}
              memory: {{ .Values.frontend.resources.limits.memory | default "128Mi" }}
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: nginx-run
          emptyDir: {}
