apiVersion: apps/v1
kind: Deployment
metadata:
  name: ft-frontend
  namespace: {{ .Release.Namespace }}
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  replicas: {{ .Values.frontend.replicas | int }}
  selector:
    matchLabels:
      app: ft-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: ft-frontend
        version: v1
        sidecar.istio.io/inject: "true"
      annotations:
        proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true}'
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      serviceAccountName: ft-service-account
      securityContext:
        runAsNonRoot: true
        runAsUser: 101  # nginx user
        fsGroup: 101    # nginx group
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
            - containerPort: 15020
              name: http-istio
          volumeMounts:
            - name: nginx-run
              mountPath: /run/nginx
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu | default "50m" }}
              memory: {{ .Values.frontend.resources.requests.memory | default "64Mi" }}
            limits:
              cpu: {{ .Values.frontend.resources.limits.cpu | default "100m" }}
              memory: {{ .Values.frontend.resources.limits.memory | default "128Mi" }}
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: nginx-run
          emptyDir: {}
