apiVersion: v1
kind: Service
metadata:
  name: ft-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: ft-frontend
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
  - port: 15020
    name: http-istio
    targetPort: 15020
  selector:
    app: ft-frontend
