apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: tpt-gateway
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "{{ .Values.ingress.host }}"
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "{{ .Values.ingress.host }}"
      tls:
        mode: SIMPLE
        credentialName: istio-system/tpt-tls
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: tpt
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
spec:
  hosts:
    - "{{ .Values.ingress.host }}"
  gateways:
    - tpt-gateway
  http:
    # API routes - à travers Nginx qui peut afficher les erreurs personnalisées
    - match:
        - uri:
            prefix: /api
      route:
        - destination:
            host: tpt-backend
            port:
              number: 8000
          headers:
            request:
              set:
                X-Forwarded-Proto: https

    # Admin routes - à travers Nginx qui peut afficher les erreurs personnalisées
    - match:
        - uri:
            prefix: /admin
      route:
        - destination:
            host: tpt-backend
            port:
              number: 8000
          headers:
            request:
              set:
                X-Forwarded-Proto: https

    # Static files - vers le serveur Nginx qui est optimisé pour servir des fichiers statiques
    - match:
        - uri:
            prefix: /static
      route:
        - destination:
            host: tpt-backend
            port:
              number: 8000
          headers:
            request:
              set:
                X-Forwarded-Proto: https

    # Media files - vers le serveur Nginx qui est optimisé pour servir des fichiers statiques
    - match:
        - uri:
            prefix: /media
      route:
        - destination:
            host: tpt-backend
            port:
              number: 8000
          headers:
            request:
              set:
                X-Forwarded-Proto: https

    # Sentry Tunnel - vers Nginx qui gère le proxy vers Sentry
    - match:
        - uri:
            exact: /tunnel
      route:
        - destination:
            host: tpt-backend
            port:
              number: 8000
          headers:
            request:
              set:
                X-Forwarded-Proto: https

    # Toutes les autres routes - vers le frontend
    - route:
        - destination:
            host: tpt-frontend
            port:
              number: 80
          headers:
            request:
              set:
                X-Forwarded-Proto: https
