apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: ft-gateway
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "{{ .Values.ingress.host }}"
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "{{ .Values.ingress.host }}"
      tls:
        mode: SIMPLE
        credentialName: ft-tls
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ft
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
spec:
  hosts:
    - "{{ .Values.ingress.host }}"
  gateways:
    - ft-gateway
  http:
    # API routes - Backend Django
    - match:
        - uri:
            prefix: /api
      route:
        - destination:
            host: ft-backend
            port:
              number: 8000
          headers:
            request:
              set:
                X-Forwarded-Proto: https

    # Toutes les autres routes - Frontend React
    - route:
        - destination:
            host: ft-frontend
            port:
              number: 80
