apiVersion: v1
kind: Service
metadata:
  name: tpt-nginx
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: tpt-nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
