apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tpt-backend-pdb
  namespace: {{ .Values.namespace }}
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      app: tpt-backend
