apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-exporter-queries
  namespace: {{ .Release.Namespace }}
data:
  queries.yaml: |
    pg_max_connections:
      query: SELECT setting::numeric as max_connections FROM pg_settings WHERE name = 'max_connections'
      metrics:
        - max_connections:
            usage: "GAUGE"
            description: "Maximum number of connections allowed"

    pg_connections:
      query: SELECT COUNT(*)::numeric as active FROM pg_stat_activity WHERE state = 'active'
      metrics:
        - active:
            usage: "GAUGE"
            description: "Number of active connections"

    pg_database_size:
      query: SELECT pg_database_size(current_database())::numeric as size_bytes
      metrics:
        - size_bytes:
            usage: "GAUGE"
            description: "Size of the current database in bytes"
