apiVersion: v1
kind: Secret
metadata:
  name: ft-secrets
  namespace: "{{ .Values.namespace }}"
type: Opaque
stringData:
  POSTGRES_PASSWORD: "{{ .Values.postgres.password }}"
  POSTGRES_USER: "{{ .Values.postgres.user }}"
  POSTGRES_DB: "{{ .Values.postgres.database }}"
  POSTGRES_HOST: "{{ .Values.postgres.host }}"
  POSTGRES_PORT: "{{ .Values.postgres.port }}"
  DJANGO_SECRET_KEY: "{{ .Values.django.secret_key }}"
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ghcr-secret
  namespace: "{{ .Values.namespace }}"
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: pumpkin-fz-wl
        envSlug: "{{ .Values.environment }}"
        secretsPath: /GHCR
      credentialsRef:
        secretName: veronica-machine-credentials
        secretNamespace: infisical
  managedSecretReference:
    secretName: ghcr-secret
    secretNamespace: "{{ .Values.namespace }}"
    creationPolicy: Owner
    secretType: kubernetes.io/dockerconfigjson
