# Valeurs par défaut
environment: production
namespace: tpt-production
image:
  repository: ghcr.io/cesar-richard-ei/turbo-pancake-tocarde-backend
  tag: latest

ingress:
  host: tocarde.fr

configMap:
  TPT_DJANGO_DEBUG: "True"
  TPT_BASE_URL: "/"
  LOG_LEVEL: "WARNING"
  DJANGO_ALLOWED_HOSTS: "*"

volumes:
  postgres:
    size: 5Gi

web:
  replicas: 1

nginx:
  config:
    serverName: tocarde.fr

postgres:
  image: postgres:17
  user: postgres
  database: tpt
  host: tpt-db
  port: 5432
  password: tpt

pdb:
  maxUnavailable: 1

istio:
  revision: default

prometheus:
  enabled: false

revisionHistoryLimit: 10

frontend:
  replicas: 1
  image:
    repository: ghcr.io/cesar-richard-ei/turbo-pancake-tocarde-backend
    tag: latest
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

django:
  secret_key: "+uochl)=pkgm#_8v0d)e&w0+0h9$d-+p)w19my_0^5om%ur#e1"