# Generated by Django 5.2.4 on 2025-07-29 12:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0014_remove_carpoolrequest_unique_passenger_trip_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="eventhostingrequest",
            unique_together=set(),
        ),
    ]
