# Generated by Django 5.2.6 on 2025-09-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0015_alter_eventhostingrequest_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="url_image",
            field=models.URLField(
                blank=True,
                help_text="URL de l'image de l'événement",
                max_length=255,
                null=True,
                verbose_name="URL de l'image",
            ),
        ),
    ]
